### ISSUE TITLE
Not working with nested media queries

### ISSUE THREAD

**Issue by simonsmith** [simonsmith/postcss-property-lookup#17]
Seeing this issue in codebases that were using the old version with no problem:

``` css
.Logo {
  text-align: center;
  display: block;
  color: inherit;
  font-family: "Yanone Kaffeesatz", "Helvetica Neue", Helvetica, Arial, sans-serif;

  @media (--md-viewport) {
    background-color: var(--color-gray-faint);
    border-right: 1px solid var(--color-gray-lighter);
    border-left: @border-right;
    padding: 5px;
  }
}
```

In the output CSS the `@border-right` value remains. I will add a test case for this tomorrow, this is just so I remember.
