### ISSUE TITLE
Interpolation of value

### ISSUE THREAD

**Issue by Ser-Gen** [simonsmith/postcss-property-lookup#22]
Some lookupped values may be unitless.
But others must use units:
```sass
/* input */

.body {
	line-height: 1.5;
	font-size: @line-height;
}
```
```css
/* output */

.body {
	line-height: 1.5;
	font-size: 1.5;
}
```

I need to get:
```css
/* output */

.body {
	line-height: 1.5;
	font-size: 1.5em;
}
```

For example, we can use this syntax `font-size: @(line-height)em;`
