### ISSUE TITLE
Issue With Nesting

### ISSUE THREAD

**Issue by AlecRust** [simonsmith/postcss-property-lookup#3]
It seems if you use this plugin in a `.Parent` selector then also use it in a nested `.Child` selector, the value in `.Parent` gets incorrectly taken from the equivalent in `.Child`.

In this case should use the `padding-left` value from `.Parent` not the one from `.Child`.

Instead this input:
```css
.Parent {
  padding-left: 5px;
  padding-right: @padding-left;

  .Child {
    padding-left: 10px;
    padding-right: @padding-left;
  }
}
```

Produces this output:
```css
.Parent {
  padding-left: 5px;
  padding-right: 10px;

  .Child {
    padding-left: 10px;
    padding-right: 10px;
  }
}
```

I've opened a PR (https://github.com/simonsmith/postcss-property-lookup/pull/2) which adds a test to reveal this issue.
