### ISSUE TITLE
Feature request: @parent

### ISSUE THREAD

**Issue by jedmao** [simonsmith/postcss-property-lookup#6]
What do you think about supporting `@parent` like so?

```scss
.foo {
    color: red;
}

.bar {
    color: @parent.foo.color; /* yields red */
}
```

Theoretically, this would only go up one level with nesting:

```scss
.foo {
    color: white;
    &:hover {
        color: red;
    }
    .baz {
        color: @parent.color;       /* yields white */
        color: @parent:hover.color; /* yields red   */
    }
}
```

I suppose it would make sense to support `@root` as well:

```scss
.foo {
    color: white;
}

.bar {
    &:hover {
        color: @root.foo.color; /* yields white */
    }
}
```
